### ISSUE TITLE
before publicizing: checklist

### ISSUE THREAD

**Issue by ctb** [dib-lab/chill-filter#12]
- [ ] ~session stuff~
- [x] better config
- [x] put temp directory elsewhere
- [x] logo
- [x] basic logging
- [x] minimal user guide
- [x] figure out timeouts, sync, whatever
