### ISSUE TITLE
manual test checklist

### ISSUE THREAD

**Issue by ctb** [dib-lab/chill-filter#13]
before "release", check:

- [ ] delete temp directory
- [ ] both abund and flat examples work

visit:
- [ ] download CSV
- [ ] download sketch
- [ ] delete sketch
- [ ] sample information page
- [ ] front page
- [ ] guide
- [ ] faq
- [ ] support forum link
